version: '3.3'
services:
  db:
    image: postgres:13.10
    env_file: ./.env
    volumes:
      - pg_data:/vat/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    # build: 
    #   context: ../backend
    #   dockerfile: Dockerfile
    image: vanyatheman/food-xdd:latest
    env_file: ./.env
    volumes:
      - static:/app/static
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    image: vanyatheman/food-xdd-front:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

volumes:
  static:
  media:
  pg_data:
  redoc:
